version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  build:
    docker:
      - image: cimg/node:16.20.1
    steps:
      - checkout
      - run:
          name: install-packages
          command: npm install
      - run:
          name: build
          command: npm run build  
      - run:
          name: place GA id
          command: |
            echo $TRACKID
            sed -i -e "s/<trackid>/${TRACKID}/g" build/index.html && rm -rf build/index.html-e
      - persist_to_workspace:
          root: ./
          paths: 
            - build/*
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - aws-s3/sync:
          from: ./build
          to: 's3://isache.com'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
workflows:
  version: 2.1
  build-deploys:
    jobs:
      - build
      - deploy:
          # type: approval
          requires:
            - build
          filters:
            branches:
              only: master
